spring:
  application:
    name: dollar-client
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
      bindings:
        prices-in-0:
          destination: dollar.api.price
          group: dollarClientGroup
server:
  port: 8083